name: datec_latam_generate_feature_code
description: Generate code for clean architecture
repository: https://github.com/datec-latam/datec_latam_generate_feature_code
version: 1.0.0
environment:
  sdk: ^3.7.0

dependencies:
  mason_cli: ^0.1.2

dev_dependencies:
  test: ^1.0.0